### ISSUE TITLE
这个例子能不能加个屏幕截图做视频源

### ISSUE THREAD

**Issue by zk0301** [AgoraIO/Agora-Video-Source-Android#9]
我想改成屏幕截图作为视频源，但是CustomizedCameraRenderer这个我没看懂啊。写法太新了吧。以前做camera都是走onPreviewFrame()得到byte[]。

屏幕截图用的是mediaprojection得到bytebuffer这个我会。怎么转成onFrameAvailable()需要的参数。这个搞不懂了。

**Comment by guohai** [comment]
内容来自屏幕的请参见 https://github.com/AgoraIO/Agora-Screen-Sharing-Android
